#####################
# Site metadata
title: Ferenk.DEV
description: Ferenk's developer site
email: fmoricz@gmail.com
author: ferenk
copyright: "Ferenc Moricz, 2024"
url: https://github.com/ferenk/ferenk.dev-web
# baseurl: https://github.com/ferenk/ferenk.dev-web
keywords: "Ferenk, dev, development, coding, github, projects"
google_analytics: GTM-T47R9MX8
#####################
# Jekyll theme config
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
show_downloads: true
header_transparent: true
night_mode: "auto"
yat:
  date_format: "%Y-%m-%d %H:%M"
lang: "en"
sitemap: true
theme_color: greenblue
brand_color: orangered
selection:
  color: "#ff00ff"
  background_color: "yellow"
code_badge:
  enabled: true
defaults:
  home:
    heading: "Ferenk.DEV main page"
    subheading: "Ferenk's developer site - my main projects"
